version: "3.8"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: highlight-api-tests
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
